services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mindmonitor'
      - 'POSTGRES_PASSWORD=17082005'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
